spring:
  application:
    name: idempotent
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 60000
    ssl: false
    ttl-in-minutes: 86400000

app:
  idempotent:
    timeout-minutes: 10
    result-expire-minutes: 1440
